"""deleted anon_tripcode

Revision ID: 835b4fa77f7a
Revises: 8df935134554
Create Date: 2023-12-07 19:22:58.809487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835b4fa77f7a'
down_revision = '8df935134554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('anon_tripcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anon_tripcode', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
