"""Initial migrasion with Post and Threads tables

Revision ID: d1601dc4689a
Revises: 
Create Date: 2023-12-06 17:17:42.373973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1601dc4689a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('post_text', sa.String(length=1024), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('anon_tripcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('count_of_posts', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=2), nullable=True),
    sa.Column('thread_bamping', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threads')
    op.drop_table('posts')
    # ### end Alembic commands ###
